### ISSUE TITLE
Versions of diskquota

### ISSUE THREAD

**Issue by RekGRpth** [greenplum-db/diskquota#308] opened 2023-03-03 11:42 UTC
Why You decided place version number to .so-file name?

**Comment by beeender** [comment] 2023-03-06 02:58
It is easier to manage upgrade/downgrade. In our official release, every latest minor version so file exists. So the diskquota works even without extension upgrade.
And it is easier for the C code maintenance. We don't have to care about backward compatibility in the C code. If there is a SQL change, we just bump the minor version.

**Comment by RekGRpth** [comment] 2023-03-06 03:28
what if PG_MODULE_MAGIC_DATA will changed and old .so-file-s have one PG_MODULE_MAGIC_DATA and new .so-file-s have another PG_MODULE_MAGIC_DATA? or You compile every version again?

**Comment by beeender** [comment] 2023-03-06 05:40
`PG_MODULE_MAGIC_DATA` why will it change? We make different releases for GP6 and GP7. It should stay the same for GP major version I think?

>  You compile every version again?

There are separated builds for GP6 and GP7 if that is the question.

**Comment by RekGRpth** [comment] 2023-03-06 05:58
If I have and use version 1.0 and I want update it to latest 2.2.0, then I need install all sequenced versions?

**Comment by beeender** [comment] 2023-03-06 06:14
> If I have and use version 1.0 and I want update it to latest 2.2.0, then I need install all sequenced versions?

No, you don't. For upgrading, you only need the so version which you are willing to upgrade to.
And actually, you can only have one diskquota so file in the `shared_preload_libraries` since there are duplicated symbols.

Check https://docs.vmware.com/en/VMware-Tanzu-Greenplum/6/greenplum-database/GUID-ref_guide-modules-diskquota.html#upgrade for more details about upgrading.

**Comment by RekGRpth** [comment] 2023-03-06 07:18
> For upgrading, you only need the so version which you are willing to upgrade to.
> And actually, you can only have one diskquota so file in the `shared_preload_libraries` since there are duplicated symbols.

If I update from 1.0 to 2.1 or to 2.2 following error occured:
```sql
alter extension diskquota update;
ERROR:  could not access file "$libdir/diskquota-2.0.so": No such file or directory
```

**Comment by RekGRpth** [comment] 2023-03-06 07:22
> Check https://docs.vmware.com/en/VMware-Tanzu-Greenplum/6/greenplum-database/GUID-ref_guide-modules-diskquota.html#upgrade for more details about upgrading.

As I understand, for updating from 1.0 to 2.1 or to 2.2, I need firstly update to 2.0, and so I need firstly install 2.0 version?

**Comment by beeender** [comment] 2023-03-06 08:01
> As I understand, for updating from 1.0 to 2.1 or to 2.2, I need firstly update to 2.0, and so I need firstly install 2.0 version?

Yes. And you need:
```
gpconfig -c shared_preload_libraries -v 'diskquota-2.0'
gpstop -ra
```

**Comment by RekGRpth** [comment] 2023-03-09 06:52
can I update diskquota from 1.0 to 2.1 (without installing 2.0) via adding symlink from diskquota-2.0.so to diskquota-2.1.so?
```sh
LC_ALL=C ls -lan diskquota*
lrwxrwxrwx 1 1000 1000      16 Mar  9 09:01 diskquota-2.0.so -> diskquota-2.1.so
-rwxr-xr-x 1 1000 1000 1459192 Mar  9 08:57 diskquota-2.1.so
```

**Comment by beeender** [comment] 2023-03-09 07:03
Since it is not by design, it may or may not work. No guarantee of that.

**Comment by RekGRpth** [comment] 2023-03-09 07:06
> it may or may not work

update is worked, but question is, what does diskquota-2.0.so do, that diskquota-2.1.so does not?

**Comment by beeender** [comment] 2023-03-09 07:14
We have some rules to make upgrading/downgrading simpler.

If there is a modification on the extension SQL file, we bump the minor version. This means we guarantee the so file compatibility among all patch versions of a specific minor release.

But it doesn't mean we guarantee 2.1 so works with 2.0 so. It might work, but it is not on purpose. And it might not work for 2.1 and 2.2.

**Comment by beeender** [comment] 2023-03-21 11:17
I am closing this issue. Feel free to reopen it if there are still questions.

Thanks!

**Closed by beeender** 2023-03-21 11:17 UTC
Labels: question
